import { useState } from 'react';
import { ArrowUpRight, Send, Search, ChevronDown, Home, Bell, MessageSquare } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import MarketingDesktop from './MarketingDesktop';
import LaunchExplorer from './LaunchExplorer';
import FinanceWorkspace from './FinanceWorkspace';
import './experience-v2.css';

const launchRecords = [
  {name:'Partner launch brief',app:'Google Docs',type:'Launch brief',logo:'google-docs.png',text:'Atlas plans a Q2 Partner Platform launch. A phased release is proposed, but Engineering has not confirmed whether the general partner experience shares affected identity code. The June launch date is a target, not an approval. Elena owns the scope decision. Product, Engineering, Security, Partner Marketing, Enablement and Operations must reconcile their dependencies.'},
  {name:'Enterprise sign-in · vendor change',app:'Slack',type:'Vendor-call account · channel thread',logo:'slack.png',text:'Alex reports that the identity vendor will change its API on May 20. Engineering has not yet verified new-user enterprise SSO against that version. Alex clarifies that this concern is scoped to enterprise SSO, not every launch deliverable. This is a reported dependency, not proof of a failed integration.'},
  {name:'Partner sales story · working deck',app:'Google Slides',type:'Presentation · draft',logo:'google-slides.png',text:'Maya, Partner Marketing, is building a sales deck explaining the launch, partner value and rollout scope. Slide 6 currently claims enterprise SSO will be available at launch. Maya must revise that unapproved draft claim while Engineering and Security assess supported behavior. The team can prepare alternate stories and workshop exercises while their final scope remains conditional. Nothing in this draft approves a public claim.'},
  {name:'Q2 partner readiness plan',app:'Google Sheets',type:'Planning spreadsheet',logo:'google-sheets.png',text:'Maya owns the sales deck; Enablement owns the workshop; Engineering owns validation; Security owns access review; Operations owns partner support coverage. The workshop and deck narrative can proceed. Enterprise SSO demonstration and final claim approval depend on validation. Team all-hands is a separate calendar appointment, not a launch approval.'},
];
export default function ExperienceV2({surface,onSurface}:{surface:string;onSurface:(s:string)=>void}) {
  const [scenario,setScenario]=useState('launch');
  const [record,setRecord]=useState<number|null>(null);
  const [drafts,setDrafts]=useState<Record<string,string>>({});
  const draft=drafts[surface]||'';
  const setDraft=(value:string)=>setDrafts(previous=>({...previous,[surface]:value}));
  const [conversations,setConversations]=useState<Record<string,string[]>>({});
  const messages=conversations[surface]||[];
  const setMessages=(value:string[])=>setConversations(previous=>({...previous,[surface]:value}));
  const [preparedViews,setPreparedViews]=useState<Record<string,boolean>>({});
  const prepared=preparedViews[surface]||false;
  const setPrepared=(value:boolean)=>setPreparedViews(previous=>({...previous,[surface]:value}));
  const [requestText,setRequestText]=useState('Sam — please verify new-user enterprise SSO against the vendor’s May 20 API version. Which tests and security review remain, and does self-service share affected code?');
  const [collapsed,setCollapsed]=useState(false);
  const [hidden,setHidden]=useState(false);
  function composer(label:string){return <form className="v2-composer" onSubmit={e=>{e.preventDefault();if(draft.trim()){setMessages([...messages,draft.trim()]);setDraft('');}}}><label>{label}<textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder={label}/></label><div><span>＋ &nbsp; ☺ &nbsp; @ &nbsp; Aa</span><button type="submit" disabled={!draft.trim()} aria-label="Send simulated message"><Send size={17}/></button></div><small>Illustration only · no live AI or messages sent</small></form>}
  function sourceButtons(){return <div className="v2-sources">{launchRecords.map((r,i)=><button key={r.name} onClick={()=>setRecord(i)}><img src={'/providers/'+r.logo} alt={r.app}/><span>{r.name}<small>{r.app} · {r.type} · Fictional</small></span><ArrowUpRight size={15}/></button>)}</div>}
  function replies(){return messages.map((m,i)=><div className="v2-local-reply" key={i}><b>You</b><p>{m}</p><b>Phossil · simulated</b><p>This preview keeps your question in this page. It does not generate a live answer. You can inspect the launch brief, compare the dependencies in Explorer, or prepare the illustrated validation request.</p></div>)}
  return <section id="experience" className="experience-v2 wrap">
    <span className="eyebrow">A connected experience</span>
    <div className="v2-heading"><h2>Different work.<br/>A shared foundation.</h2><p>Start in a conversation, beside a deliverable, or with a question in Workspace. Choose the situation separately from the view. Phossil follows the work—not a prescribed sequence of screens.</p></div>
    <div className="v2-scenario-picker" role="group" aria-label="Choose a fictional scenario"><button aria-pressed={scenario==='launch'} onClick={()=>setScenario('launch')}><b>01 · A Q2 product launch</b><span>Partner marketing, product, engineering and leadership</span></button><button aria-pressed={scenario==='finance'} onClick={()=>setScenario('finance')}><b>02 · Growth and cash</b><span>Finance, sales, hiring and operating commitments</span></button></div>
    <div hidden={scenario!=='finance'}><p className="v2-context">A separate fictional finance situation · Workspace view. The launch remains available above.</p><FinanceWorkspace/></div><div hidden={scenario!=='launch'}>
    <div className="v2-context"><span className="eyebrow">Fictional company · Atlas · Q2 Partner Platform launch</span><h3>The launch is one initiative.<br/>The work does not all depend on the same thing.</h3><p>Maya is preparing partner sales materials. A vendor change raises a question about enterprise sign-in. Elena needs to understand which commitments, teams and deliverables are affected—and which work can still move in Q2.</p></div>
    <div className="v2-view-picker" role="group" aria-label="Launch views">{['messaging','flow','explorer','workspace'].map(s=><button key={s} aria-pressed={surface===s} onClick={()=>onSurface(s)}>{s==='messaging'?<img src="/providers/slack.png" alt=""/>:null}{({messaging:'Messaging',flow:'Flow Card',explorer:'Explorer',workspace:'Workspace'} as Record<string,string>)[s]}</button>)}<small>Same launch · different ways in</small></div>
    {surface==='messaging' && <div className="v2-slack">
      <aside className="v2-slack-sidebar"><h3>Atlas <ChevronDown size={17}/></h3><p><Home size={16}/> Home</p><p><MessageSquare size={16}/> DMs</p><p><Bell size={16}/> Activity</p><p>••• &nbsp; More</p><h4>⌄ &nbsp; Channels</h4><p># &nbsp; product</p><p className="selected"># &nbsp; q2-launch</p><p># &nbsp; partner-marketing</p><p># &nbsp; leadership</p><h4>⌄ &nbsp; Direct messages</h4><p><img src="/brand/symbol-dark.svg" alt=""/> Phossil <small>APP</small></p><p>● &nbsp; Maya Chen</p><p>● &nbsp; Sam Park</p><p>● &nbsp; Elena Rivera</p></aside>
      <div className="v2-slack-main"><header><strong># q2-launch</strong><span>12 members &nbsp; <Search size={18}/> &nbsp; •••</span></header>
        <div className="v2-slack-messages"><article className="v2-slack-message"><span className="v2-avatar">AR</span><div><b>Alex Rivera <small>10:14 AM</small></b><p>Just spoke with the identity vendor. Their API changes on May 20. What does this mean for our Q2 launch?</p></div></article>
        <article className="v2-slack-message"><span className="v2-avatar phossil"><img src="/brand/symbol-dark.svg" alt="Phossil"/></span><div><b>Phossil <small>APP · 10:15 AM</small></b><p>This may affect enterprise sign-in. It does not automatically block the entire launch.</p><ul><li><strong>Known:</strong> the vendor change is reported for May 20.</li><li><strong>Not yet verified:</strong> new-user enterprise SSO compatibility.</li><li><strong>Work that can continue:</strong> the partner story and workshop preparation, keeping SSO claims conditional.</li></ul><div className="v2-suggested"><strong>Suggested next move</strong><p>Ask Sam in Engineering to verify the affected path, then identify any changes to the demo and sales claims.</p><div className="v2-action-row"><button onClick={()=>setPrepared(true)}>Prepare request</button><button onClick={()=>setRecord(1)}>Inspect source</button><button onClick={()=>onSurface('explorer')}>See in Phossil</button></div></div></div></article>
        <article className="v2-slack-message"><span className="v2-avatar">AR</span><div><b>Alex Rivera <small>10:22 AM</small></b><p>Only enterprise SSO is affected. Don’t hold up the other launch work.</p></div></article>
        <article className="v2-slack-message"><span className="v2-avatar phossil"><img src="/brand/symbol-dark.svg" alt="Phossil"/></span><div><b>Phossil <small>APP · 10:23 AM</small></b><p>I’ve kept Alex’s clarification as an account, not a verified boundary. Engineering still needs to check compatibility and whether self-service shares affected code. Maya can keep developing the deck without publishing the unverified claim.</p><button className="v2-inline-button" onClick={()=>{onSurface('flow');setHidden(false)}}>Open Maya’s Flow Card ↗</button></div></article>{replies()}{prepared&&<div className="v2-request"><strong>Draft request · not sent</strong><textarea aria-label="Draft validation request" value={requestText} onChange={e=>setRequestText(e.target.value)}/><button onClick={()=>setPrepared(false)}>Keep as draft and close</button><small>No Slack connection. This example cannot send.</small></div>}</div>{composer('Message #q2-launch')}</div>
    </div>}
    {surface==='flow' && <div className="flow-scene v2-flow-scene"><MarketingDesktop/>{hidden?<button className="button deep" onClick={()=>setHidden(false)}>Reopen Flow Card</button>:<aside className="flow-card v2-flow-card"><div className="flow-card-head"><img src="/brand/symbol-light.svg" alt="Phossil"/><span>Flow Card</span><button aria-label="Collapse or expand Flow Card" onClick={()=>setCollapsed(!collapsed)}>−</button><button aria-label="Dismiss Flow Card" onClick={()=>setHidden(true)}>×</button></div><small>Maya · Partner Marketing · Your view</small><h3>Keep the partner story moving.</h3>{!collapsed&&<><p>You were building the Q2 sales deck. The enterprise sign-in question affects one claim and the demo—while shared-code impact remains unverified.</p><div className="v2-flow-change"><b>What changed</b><p>Alex narrowed the concern to enterprise SSO. Sam still needs to verify the new-user path.</p><b>What you can work on now</b><p>Prepare alternate value stories and enablement outlines. Keep the SSO slide conditional and hold the final demo claim for review.</p></div><div className="v2-action-row"><button onClick={()=>setPrepared(true)}>Prepare deck note</button><button onClick={()=>onSurface('explorer')}>Explore dependencies</button></div>{prepared&&<div className="v2-request"><b>Suggested note · not applied to Slides</b><p>Enterprise SSO demonstration pending validation. General partner value story can proceed.</p><button onClick={()=>setPrepared(false)}>Keep note in this preview</button></div>}{sourceButtons()}{replies()}{composer('Ask about this deck or the launch…')}</>}</aside>}</div>}
    <div hidden={surface!=='explorer'}><LaunchExplorer/></div>
    {surface==='workspace'&&<div className="v2-launch-workspace"><aside>Phossil Workspace<br/><br/>Home<br/><br/>Company<br/><br/>Movement<br/><br/><b>Work</b><br/><br/><button onClick={()=>onSurface('explorer')}>Explorer ↗</button><br/><br/>Memory</aside><div><small>WORK / Q2 PARTNER PLATFORM</small><h3>Coordinate the launch without freezing every team.</h3><p>Elena · scope decision / Sam · validation / Maya · partner story / Security · access review / Operations · coverage</p><div className="v2-work-grid"><article><b>Move now</b><p>Partner narrative, training outline, capacity planning and validation preparation.</p></article><article><b>Resolve before commitment</b><p>Enterprise SSO compatibility, demo scope, final claims and release authority.</p></article><article><b>Carry forward</b><p>Record why scope changes, check what was actually released, then review partner feedback before reusing the launch approach.</p></article></div><h4>Sources behind this shared picture</h4>{sourceButtons()}<button className="button deep" onClick={()=>onSurface('explorer')}>Explore the reasoning ↗</button></div></div>}
    </div>
    <p className="v2-disclosure">Interactive design illustration. People, records and outcomes are synthetic. App interfaces are illustrative, not connected services. No live AI, messages, approvals, payments or edits to external tools occur.</p>
    <Dialog open={record!==null} onOpenChange={open=>{if(!open)setRecord(null)}}><DialogContent>{record!==null&&<><DialogTitle>{launchRecords[record].name}</DialogTitle><DialogDescription>{launchRecords[record].app} · {launchRecords[record].type} · Synthetic source</DialogDescription><p>{launchRecords[record].text}</p><small>This is the complete authored record for this illustration, not a file in your apps.</small></>}</DialogContent></Dialog>
  </section>
}
