import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ChevronRight, X } from 'lucide-react';
import './finance-workspace.css';

const financeRecords = [
  { id: 'bank', logo: 'google-sheets.png', app: 'Google Sheets', type: 'Bank transactions · CSV import', title: 'Opening cash reconciliation', owner: 'Nora · Controller', excerpt: 'Reconciled opening cash: $2,400,000. This is the opening balance for the illustrated 13-week model, not an estimate of future collections.', limit: 'A balance at one point in time; not revenue or available spending authority.' },
  { id: 'forecast', logo: 'google-sheets.png', app: 'Google Sheets', type: '13-week cash forecast · spreadsheet', title: 'Base case and collection sensitivity', owner: 'Eli · FP&A', excerpt: 'Baseline cash receipts: $1,200,000. Baseline payments: $2,000,000. Closing cash: $1,600,000. Receipts include a $450,000 enterprise collection. If it arrives outside this horizon, closing cash becomes $1,150,000 before proposed hires.', limit: 'A planning model. Receipt dates and planned payments remain assumptions.' },
  { id: 'contract', logo: 'hubspot.svg', app: 'HubSpot', type: 'CRM deal · signed contract attachment (PDF)', title: 'Enterprise expansion · collection timing', owner: 'Mara · Account lead', excerpt: 'Signed expansion contract: $450,000 expected cash receipt within the forecast horizon. Customer procurement has not confirmed the payment date. Commercial commitment is recorded; cash has not been received.', limit: 'A signed contract does not confirm receipt timing or settle revenue recognition.' },
  { id: 'payroll', logo: 'google-sheets.png', app: 'Google Sheets', type: 'Payroll plan · CSV import', title: 'Proposed hiring cohort', owner: 'June · People Operations', excerpt: 'The proposed hiring cohort adds $180,000 of cash payments within the 13-week horizon. Moving one proposed start date outside this horizon reduces that amount by $60,000. Existing payroll is already in baseline payments; these are incremental amounts.', limit: 'Timing scenarios, not approved offers. Deferral also has a delivery-capacity consequence.' },
  { id: 'cloud', logo: 'google-drive.png', app: 'Google Drive', type: 'Cloud supplier invoice · PDF', title: 'Committed infrastructure payment', owner: 'Theo · Engineering Operations', excerpt: 'A $240,000 infrastructure payment is included in the $2,000,000 baseline payments. It is a committed payment in this case; do not add it again or treat it as discretionary savings without checking the supplier agreement.', limit: 'Invoice amount is already counted. No supplier concession has been confirmed.' },
  { id: 'policy', logo: 'google-docs.png', app: 'Google Docs', type: 'Planning policy · document', title: 'Internal cash floor and decision rights', owner: 'Leah · CFO', excerpt: 'Use $1,000,000 as the internal planning cash floor for this illustrative period. FP&A prepares scenarios; the CFO decides whether to approve changes to hiring timing. The CEO resolves a material delivery-priority conflict. The floor is an internal choice, not an external accounting standard.', limit: 'An internal planning constraint. No hiring change is approved by this record alone.' },
  { id: 'thread', logo: 'slack.png', app: 'Slack', type: 'Finance / People / Engineering · message thread', title: 'Growth plan and delivery trade-off', owner: 'Leah, June & Theo', excerpt: 'Finance asks for a downside cash case before approving start dates. People Operations needs a decision before issuing offers. Engineering asks whether delaying a hire would move a customer milestone. No revised start dates, offers, or customer commitments have been authorized.', limit: 'A coordination request, not a decision or a verified business outcome.' },
];

const financeTabs = ['Overview', 'Sources', 'Options & decision', 'Action & learning'] as const;
type FinanceTab = typeof financeTabs[number];

export default function FinanceWorkspace() {
  const [tab, setTab] = useState<FinanceTab>('Overview');
  const [delayed, setDelayed] = useState(true);
  const [hires, setHires] = useState(true);
  const [defer, setDefer] = useState(false);
  const [inspected, setInspected] = useState<string | null>(null);
  const [prepared, setPrepared] = useState(false);
  const inspector = useRef<HTMLElement>(null);
  useEffect(() => { if (inspected) inspector.current?.focus(); }, [inspected]);
  const record = financeRecords.find((item) => item.id === inspected);
  const receipts = 1200 - (delayed ? 450 : 0);
  const payments = 2000 + (hires ? 180 - (defer ? 60 : 0) : 0);
  const closing = 2400 + receipts - payments;
  const money = (value: number) => `$${(value / 1000).toFixed(2)}m`;

  const source = (id: string) => {
    const item = financeRecords.find((entry) => entry.id === id)!;
    return <button className="finance-source" key={id} onClick={() => setInspected(id)}><img src={`/providers/${item.logo}`} alt="" /><span><strong>{item.title}</strong><small>{item.app} · {item.type}</small></span><ArrowUpRight size={16} aria-hidden="true" /></button>;
  };

  return <div className="finance-workspace">
    <header className="finance-top"><span><img src="/brand/symbol-light.svg" alt="Phossil" /> Workspace <ChevronRight size={14} /> Atlas / Finance</span><small>Synthetic company · prepared example</small></header>
    <div className="finance-layout">
      <aside className="finance-sidebar"><span className="finance-eyebrow">ATLAS</span><span>Company</span><span>Movement</span><strong>Work</strong><span>Explorer</span><span>Memory</span><small>Navigation shown for context.<br />Explore this case using the tabs.</small></aside>
      <main className="finance-main">
        <div className="finance-heading"><div><span className="finance-eyebrow">Finance · People · Sales · Engineering</span><h2>Growth is up.<br />Can we fund the next commitments?</h2><p>Leah, the CFO, needs to reconcile hiring plans, customer collections, and committed spending—not mistake commercial growth for cash in the bank.</p></div><span className="finance-pending">Decision pending</span></div>
        <nav className="finance-tabs" aria-label="Finance case views">{financeTabs.map((item) => <button key={item} aria-pressed={tab === item} onClick={() => setTab(item)}>{item}</button>)}</nav>

        {tab === 'Overview' && <section className="finance-panel">
          <div className="finance-account"><span className="finance-eyebrow">Current understanding · correctable</span><h3>The hiring plan works in the base case. Collection timing changes the answer.</h3><p>One enterprise receipt may fall outside the next 13 weeks. Add the proposed hires, and projected closing cash drops below the internal floor. Delaying one start date restores only a narrow margin—and may affect Engineering’s delivery plan.</p><div className="finance-inline-sources">{source('forecast')}{source('contract')}</div></div>
          <div className="finance-scenario-grid"><div><h3>Test the assumptions</h3><p className="finance-muted">Change the forecast, not the underlying records.</p><label><input type="checkbox" checked={delayed} onChange={(event) => setDelayed(event.target.checked)} /> $450k collection arrives after this horizon</label><label><input type="checkbox" checked={hires} onChange={(event) => setHires(event.target.checked)} /> Include $180k proposed hiring payments</label><label><input type="checkbox" checked={defer} disabled={!hires} onChange={(event) => setDefer(event.target.checked)} /> Defer one start date: $60k less this period</label><p className="finance-muted">Deferring a payment is not eliminating its cost. Customer timing and delivery capacity still need confirmation.</p></div>
            <div className="finance-calculation" aria-live="polite"><span className="finance-eyebrow">13-week cash bridge · illustrative</span><dl><div><dt>Opening reconciled cash</dt><dd>$2.40m</dd></div><div><dt>Forecast receipts</dt><dd>+ {money(receipts)}</dd></div><div><dt>Forecast payments</dt><dd>− {money(payments)}</dd></div><div className="finance-total"><dt>Projected closing cash</dt><dd>{money(closing)}</dd></div><div><dt>Internal planning floor</dt><dd>$1.00m</dd></div></dl><strong className={closing < 1000 ? 'finance-warning' : 'finance-margin'}>{closing < 1000 ? `$${((1000 - closing) * 1000).toLocaleString()} below the floor` : `$${((closing - 1000) * 1000).toLocaleString()} above the floor`}</strong><small>This is the closing balance, not the lowest weekly balance. Weekly cash troughs and uncertainty still need review.</small></div>
          </div><button className="finance-primary" onClick={() => setTab('Options & decision')}>Compare the decision and its trade-offs <ChevronRight size={16} /></button>
        </section>}

        {tab === 'Sources' && <section className="finance-panel"><h3>Inspect what this understanding rests on.</h3><p>Seven synthetic records across financial files, commercial systems, and team conversations. App logos identify where the illustrated records are viewed; they are not connected integrations.</p><div className="finance-record-grid">{financeRecords.map((item) => source(item.id))}</div><p className="finance-note">These records are authored examples, not actual Atlas documents. The inspector shows their complete synthetic content and limits.</p><p className="finance-research">Why this is a realistic problem: recurring-revenue metrics are not immediate cash flow. <a href="https://support.stripe.com/questions/calculating-monthly-recurring-revenue-%28mrr%29-in-billing" target="_blank" rel="noreferrer">Read Stripe’s explanation of MRR <ArrowUpRight size={14} /></a> The company, figures, and decisions here are invented—not a reported customer case.</p></section>}

        {tab === 'Options & decision' && <section className="finance-panel"><span className="finance-eyebrow">A decision package, not automatic approval</span><h3>Which commitment can change—and who decides?</h3><div className="finance-table-scroll"><table><caption>Comparable cases: all assume the $450k receipt misses the horizon.</caption><thead><tr><th>Option</th><th>Closing cash</th><th>What needs judgment</th></tr></thead><tbody><tr><td>No new hiring payments in this horizon</td><td>$1.15m</td><td>Delivery capacity and hiring commitments need review.</td></tr><tr><td>Start the full proposed cohort</td><td>$0.97m</td>Below the internal floor; requires revisiting the plan.</tr><tr><td>Defer one start date</td><td>$1.03m</td>Only $30k above the floor; delivery impact unresolved.</tr></tbody></table></div><div className="finance-owner-grid"><article><small>Mara · Sales</small><h4>Verify collections</h4><p>Confirm procurement and invoice status in the CRM. Do not turn a commercial promise into a bank receipt.</p>{source('contract')}</article><article><small>June + Theo · People / Engineering</small><h4>Resolve the delivery trade-off</h4><p>Compare the proposed start date with staffing needs. Identify the milestone affected before presenting a timing change.</p>{source('payroll')}</article><article><small>Leah · CFO</small><h4>Decide within authority</h4><p>Review weekly cash lows, timing uncertainty, and delivery impact. Escalate a material priority conflict to the CEO.</p>{source('policy')}</article></div><button className="finance-primary" onClick={() => { setPrepared(true); setTab('Action & learning'); }}>Prepare a coordination brief <ChevronRight size={16} /></button><p className="finance-note">Local illustration only. No offer, payment, approval, or message is sent.</p></section>}

        {tab === 'Action & learning' && <section className="finance-panel"><span className="finance-eyebrow">Keep work moving in its existing tools</span><h3>{prepared ? 'Coordination brief prepared. Nothing sent.' : 'Prepare the next work. Keep the decision open.'}</h3><p>The AI can assemble the assumptions, supporting records, and questions. It does not approve the hiring plan or treat forecast cash as an observed result.</p><div className="finance-action-list"><article><img src="/providers/slack.png" alt="Slack" /><div><h4>Coordinate in the finance thread</h4><p>Ask Mara for payment timing and June / Theo for the start-date trade-off. Leah reviews the brief before it is shared.</p><span>Draft only · send requires review</span></div></article><article><img src="/providers/google-sheets.png" alt="Google Sheets" /><div><h4>Revise the model where Finance works</h4><p>Eli updates weekly receipt and payment assumptions after confirmation. Keep baseline commitments counted once and record what changed.</p><span>Proposed model update · not executed</span></div></article><article><img src="/providers/google-docs.png" alt="Google Docs" /><div><h4>Record the decision and later compare actuals</h4><p>Capture the approved option, reasoning, conditions, and owner. Reconcile actual bank receipts and payroll against the forecast before reusing the lesson.</p><span>Decision and outcomes not yet available</span></div></article></div>{!prepared && <button className="finance-primary" onClick={() => setPrepared(true)}>Prepare the local brief</button>}{prepared && <div className="finance-brief"><h4>Brief for Leah’s review</h4><p>Confirm the $450k collection date. Assess the delivery impact of deferring one hire. Review the $30k closing margin and weekly cash troughs before choosing a plan. Owners: Mara, June, Theo, and Eli. Decision owner: Leah.</p><p><strong>Open:</strong> receipt timing, revised staffing impact, authorization, and actual outcomes.</p></div>}<div className="finance-learning"><h4>What could become reusable understanding?</h4><p>How collection timing interacts with hiring and delivery commitments—not a rule that growth should stop or that every hire should be delayed. Future human and AI work can reuse the reviewed reasoning, then check fresh balances, obligations, permissions, and circumstances.</p></div></section>}

        {record && <aside ref={inspector} tabIndex={-1} className="finance-inspector" aria-label={`Synthetic source: ${record.title}`}><header><span className="finance-eyebrow">Complete synthetic record</span><button onClick={() => setInspected(null)} aria-label="Close source inspector"><X size={18} /></button></header><h3>{record.title}</h3><p className="finance-source-meta"><img src={`/providers/${record.logo}`} alt="" /> {record.app} · {record.type}</p><small>{record.owner} · fictional</small><blockquote>{record.excerpt}</blockquote><p><strong>Limit:</strong> {record.limit}</p><p className="finance-note">No original external file exists. This is the full authored record used in this example.</p></aside>}
        <footer className="finance-footer">Interactive synthetic planning example · not live AI or financial advice. No systems are connected; no business actions are taken.</footer>
      </main>
    </div>
  </div>;
}
