import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Minus, Plus, Maximize2, Send, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import './launch-explorer.css';

const workstreams = [
  { id: 'scope', team: 'Product', title: 'One launch, two release paths', owner: 'Elena · launch decision', status: 'Proposal · not approved', x: 380, y: 165, logo: 'google-docs.png', app: 'Google Docs', type: 'Planning document', file: 'Atlas Q2 launch options', date: 'May 8', text: 'The current proposal separates a June self-service launch from an enterprise SSO release. No launch scope has been approved. Product must confirm that self-service has no dependency on the enterprise SSO path. Elena owns the launch scope decision after Engineering, Security and Operations provide their assessments.', rationale: 'Separate the launch promise from the technical release paths. A phased plan may preserve Q2 movement without claiming enterprise readiness.', unknown: 'Does self-service really remain independent of enterprise SSO? Engineering has not confirmed this.', next: 'Ask Engineering to confirm the dependency before choosing a release path.' },
  { id: 'engineering', team: 'Engineering', title: 'SSO compatibility is unverified', owner: 'Sam · engineering assessment', status: 'Tests incomplete', x: 35, y: 405, logo: 'github.svg', app: 'GitHub', type: 'Pull request · test report', file: 'PR 142 · Atlas identity adapter', date: 'May 9', text: 'Unit tests pass for the adapter. The vendor will change its enterprise SSO API on May 20. End-to-end tests against the new API have not run. This report does not establish release readiness. Sam is assessing whether the self-service path shares affected identity code.', rationale: 'A green unit-test check cannot settle whether customer sign-in will work after the vendor change. The shared-code question also affects the proposed phased launch.', unknown: 'End-to-end compatibility and the shared-code impact remain unknown.', next: 'Draft a request for the new-API test result and the self-service dependency assessment.' },
  { id: 'security', team: 'Security', title: 'Sign-off follows integration testing', owner: 'Ari · security reviewer', status: 'Review pending', x: 380, y: 405, logo: 'jira.svg', app: 'Jira', type: 'Security review issue', file: 'SEC-38 · Identity release review', date: 'May 9', text: 'The enterprise release requires an integration test result and a completed security review. Ari has not approved the release. A slot is provisionally held for May 23; it must be reconfirmed if the test delivery date changes. Preparatory reviews can proceed before that slot.', rationale: 'Security review depends on a meaningful test result, not just a date on the launch plan. Preparation can continue while release authority remains withheld.', unknown: 'The review slot may move if the test result arrives late.', next: 'Coordinate a test handoff and reconfirm the review slot; do not mark the release approved.' },
  { id: 'marketing', team: 'Partner Marketing', title: 'The sales deck promises too much', owner: 'Maya · partner marketing', status: 'Draft claims need revision', x: 725, y: 405, logo: 'google-slides.png', app: 'Google Slides', type: 'Presentation · slide 6', file: 'Atlas partner sales deck', date: 'May 9', text: 'Slide 6 currently says “Enterprise SSO available at launch.” That is draft copy, not an approved capability claim. The partner webinar is penciled in for June 5. Maya can prepare alternate slide copy and partner FAQ responses now; final messaging depends on the approved launch scope.', rationale: 'The deck, webinar and release plan need the same scope. Changing one claim may affect partner expectations and Sales conversations, even while other content remains usable.', unknown: 'Which release path will Elena approve, and has any draft claim already reached partners?', next: 'Prepare two clearly labeled messaging variants and check whether the draft has been shared.' },
  { id: 'enablement', team: 'Sales Enablement', title: 'Training needs an honest demo path', owner: 'Jordan · enablement', status: 'Materials in preparation', x: 35, y: 680, logo: 'slack.png', app: 'Slack', type: 'Channel thread · #enablement', file: 'June partner training discussion', date: 'May 9', text: 'Jordan is building the June training session. The current exercise uses enterprise SSO. A self-service exercise could be prepared as an alternative, but Product must confirm the supported path. Training can explain limitations; it must not teach an unverified feature as available.', rationale: 'Training can progress through alternate exercises rather than wait for every launch question. Its final demo path depends on scope and verified behavior.', unknown: 'The alternate exercise has not yet been tested with a partner-facing audience.', next: 'Draft the self-service exercise and request a Product review before scheduling the final session.' },
  { id: 'operations', team: 'Partner Operations', title: 'The same specialist is booked twice', owner: 'Priya · operations', status: 'Capacity unresolved', x: 380, y: 680, logo: 'google-sheets.png', app: 'Google Sheets', type: 'Spreadsheet · June staffing', file: 'Partner launch coverage plan', date: 'May 9', text: 'The June plan assigns the same onboarding specialist to Atlas launch support and an existing partner migration. Both reservations are tentative. Priya is comparing a narrower launch cohort with temporary coverage; neither option has been agreed. The staffing plan must not count one person as two available people.', rationale: 'Even a technically ready release could exceed delivery capacity. Scope, training demand and staffing must be considered together.', unknown: 'Can either commitment move, or can qualified temporary coverage be secured?', next: 'Compare coverage for each launch option without double-counting the shared specialist.' },
  { id: 'finance', team: 'Finance', title: 'Budget headroom is not spending authority', owner: 'Dev · finance partner', status: 'Cost options requested', x: 725, y: 680, logo: 'google-sheets.png', app: 'Google Sheets', type: 'Spreadsheet · forecast scenario', file: 'Q2 launch investment scenarios', date: 'May 9', text: 'The base forecast excludes temporary launch support. A narrower cohort and temporary coverage need separate cost estimates. Budget headroom shown in this planning sheet does not approve new spending. Dev will compare the options against the current forecast and the Finance approver will decide on any incremental commitment.', rationale: 'The staffing solution may change cost and timing. Finance can compare alternatives before a scope decision without turning a forecast into a purchase authorization.', unknown: 'Temporary support cost and its effect on the latest forecast are not yet known.', next: 'Request the cost assumptions and compare the options; keep incremental spending unapproved.' },
];

const prepared = [
  { question: 'What can keep moving in Q2?', answer: 'Marketing can draft alternate claims, Enablement can prepare a self-service exercise, and Operations and Finance can compare coverage options now. A release decision still needs Engineering’s dependency assessment, the relevant tests, Security review and Elena’s scope decision. These are parallel moves, not a recommendation to launch.' },
  { question: 'Why not just delay the whole launch?', answer: 'A full delay is one option, not the only established answer. The phased option depends on self-service being independent of the affected SSO code. That has not been confirmed. Compare both options against partner commitments, staffing and cost before deciding; the map keeps that assumption visible.' },
  { question: 'What reasoning should we carry forward?', answer: 'Keep the distinction between passing unit tests and release readiness, the dependency behind each launch claim, and the capacity assumptions behind the plan. After a decision and actual delivery, compare what happened with those assumptions. There is no verified launch outcome in these May 9 records yet.' },
];

export default function LaunchExplorer() {
  const [selected, setSelected] = useState('scope');
  const [sourceId, setSourceId] = useState<string | null>(null);
  const [zoom, setZoom] = useState(0.55);
  const [space, setSpace] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [draft, setDraft] = useState('');
  const [messages, setMessages] = useState<{ role: string; text: string }[]>([]);
  const viewport = useRef<HTMLDivElement>(null);
  const hover = useRef(false);
  const drag = useRef<{ x: number; y: number; left: number; top: number } | null>(null);
  const active = workstreams.find(item => item.id === selected)!;
  const record = workstreams.find(item => item.id === sourceId);
  const fit = () => {
    const el = viewport.current;
    if (el) { setZoom(Math.max(0.2, Math.min((el.clientWidth - 24) / 1070, (el.clientHeight - 24) / 960, 1))); el.scrollTo(0, 0); }
  };
  useEffect(() => {
    const el = viewport.current;
    if (!el) return;
    const observer = new ResizeObserver(() => {
      setZoom(Math.max(0.2, Math.min((el.clientWidth - 24) / 1070, (el.clientHeight - 24) / 960, 1)));
    });
    observer.observe(el);
    const down = (event: KeyboardEvent) => {
      if (event.code === 'Space' && hover.current && !(event.target instanceof HTMLElement && event.target.closest('input,textarea,button,[contenteditable="true"]'))) { event.preventDefault(); setSpace(true); }
    };
    const up = (event: KeyboardEvent) => { if (event.code === 'Space') setSpace(false); };
    const blur = () => { setSpace(false); setDragging(false); drag.current = null; };
    window.addEventListener('keydown', down); window.addEventListener('keyup', up); window.addEventListener('blur', blur);
    return () => { observer.disconnect(); window.removeEventListener('keydown', down); window.removeEventListener('keyup', up); window.removeEventListener('blur', blur); };
  }, []);
  const ask = (text: string, answer?: string) => {
    if (!text.trim()) return;
    setMessages(previous => [...previous, { role: 'You', text: text.trim() }, { role: 'Phossil · simulated', text: answer ?? 'Your question stays in this local illustration; no live AI is connected. Choose a prepared question to explore the launch reasoning, or select a workstream to inspect its source and unresolved assumptions.' }]);
    setDraft('');
  };
  return <div className="launch-explorer">
    <header className="launch-heading"><div><small>EXPLORER · ATLAS PARTNER PLATFORM</small><h3>What can responsibly move in Q2?</h3></div><span>Elena · launch leader<br /><small>Fictional records · as of May 9</small></span></header>
    <div className="launch-layout">
      <aside className="launch-chat" aria-label="Explorer conversation">
        <div className="launch-chat-scroll"><p className="launch-chat-label">EXPLORE WITH PHOSSIL</p><div className="launch-user-message"><small>Elena asks</small><p>I see a launch date, a sales deck and passing tests. What actually needs to line up—and what can the teams keep doing now?</p></div>
          <div className="launch-reply"><img src="/brand/symbol-light.svg" alt="Phossil" /><p>The teams are working toward the same launch, but their deliverables rely on different assumptions. The proposed phased launch could preserve Q2 progress—if the self-service path is independent of the SSO change.</p><p>Select a workstream to see the reasoning, the responsible person and what is still unknown.</p><button onClick={() => setSourceId('scope')}>Inspect the launch proposal <ArrowUpRight size={14}/></button></div>
          <div aria-live="polite">{messages.map((message, i) => <div key={i} className={message.role === 'You' ? 'launch-user-message' : 'launch-reply'}><small>{message.role}</small><p>{message.text}</p></div>)}</div>
        </div>
        <div className="launch-compose"><div className="launch-question-list">{prepared.map(item => <button key={item.question} onClick={() => ask(item.question, item.answer)}>{item.question}</button>)}</div><form onSubmit={event => { event.preventDefault(); ask(draft); }}><label htmlFor="launch-question">Ask about this launch</label><textarea id="launch-question" value={draft} onChange={event => setDraft(event.target.value)} placeholder="Explore a question, challenge a connection…" rows={3}/><div><small>Local demonstration · not live AI</small><button type="submit" disabled={!draft.trim()} aria-label="Send local example message"><Send size={17}/></button></div></form></div>
      </aside>
      <section className="launch-map" aria-label="Launch reasoning canvas">
        <div className="launch-toolbar"><span>Teams, deliverables & dependencies</span><div><button aria-label="Zoom out launch canvas" onClick={() => setZoom(value => Math.max(0.2, value - 0.1))}><Minus size={16}/></button><output>{Math.round(zoom * 100)}%</output><button aria-label="Zoom in launch canvas" onClick={() => setZoom(value => Math.min(1.5, value + 0.1))}><Plus size={16}/></button><button onClick={fit} aria-label="Fit launch canvas"><Maximize2 size={16}/></button></div></div>
        <div ref={viewport} className={`launch-viewport${space ? ' launch-grab' : ''}${dragging ? ' launch-grabbing' : ''}`} tabIndex={0} aria-label="Launch canvas. Scroll to pan, or hold Space and drag. Arrow keys pan when focused." onMouseEnter={() => { hover.current = true; }} onMouseLeave={() => { hover.current = false; }} onKeyDown={event => { if (event.target !== event.currentTarget) return; const directions: Record<string, number[]> = { ArrowLeft: [-80, 0], ArrowRight: [80, 0], ArrowUp: [0, -80], ArrowDown: [0, 80] }; const direction = directions[event.key]; if (direction) { event.preventDefault(); event.currentTarget.scrollBy(direction[0], direction[1]); } }} onPointerDown={event => { if (!space || event.button !== 0) return; event.preventDefault(); const el = event.currentTarget; drag.current = { x: event.clientX, y: event.clientY, left: el.scrollLeft, top: el.scrollTop }; el.setPointerCapture(event.pointerId); setDragging(true); }} onPointerMove={event => { if (!drag.current) return; event.currentTarget.scrollLeft = drag.current.left + drag.current.x - event.clientX; event.currentTarget.scrollTop = drag.current.top + drag.current.y - event.clientY; }} onPointerUp={event => { drag.current = null; setDragging(false); if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); }} onPointerCancel={() => { drag.current = null; setDragging(false); }}>
          <div className="launch-scaled-space" style={{ width: 1070 * zoom, height: 960 * zoom }}><div className="launch-world" style={{ transform: `scale(${zoom})` }}>
            <div className="launch-map-question"><small>Q2 AMBITION · SCOPE NOT YET APPROVED</small><strong>Launch a partner-ready platform.<br />Do not confuse progress with readiness.</strong></div>
            <svg className="launch-connectors" viewBox="0 0 1070 960" aria-hidden="true"><path d="M530 125V165 M530 355V380H185V405 M530 380V405 M530 380H875V405 M185 610V655H530V680 M530 610V630H185V680 M875 610V680 M530 655H875"/></svg>
            <div className="launch-connection-note">Read together: release scope, verified behavior and external commitments</div>
            {workstreams.map(item => <button key={item.id} className={`launch-node${selected === item.id ? ' launch-node-selected' : ''}`} style={{ left: item.x, top: item.y }} aria-pressed={selected === item.id} onClick={() => { if (!space) setSelected(item.id); }}><small>{item.team}</small><strong>{item.title}</strong><span>{item.status}</span><footer><img src={'/providers/' + item.logo} alt=""/>{item.app} · {item.type}<ArrowUpRight size={14}/></footer></button>)}
            <p className="launch-map-footnote">Lines indicate dependencies to investigate, not a proven causal chain. Select any workstream.</p>
          </div></div>
        </div>
        <div className="launch-map-hint">One connected investigation. No single approval makes every workstream ready.<span>Space + drag to pan</span></div>
        <aside className="launch-inspector" aria-live="polite"><div className="launch-inspector-title"><div><small>{active.team} · {active.owner}</small><h4>{active.title}</h4></div><button onClick={() => setSourceId(active.id)}>Inspect source <ArrowUpRight size={15}/></button></div><div className="launch-inspector-grid"><p><strong>Why this matters</strong>{active.rationale}</p><p><strong>Still unresolved</strong>{active.unknown}</p><p><strong>Possible next move · not sent</strong>{active.next}</p></div></aside>
      </section>
    </div>
    <Dialog open={sourceId !== null} onOpenChange={open => { if (!open) setSourceId(null); }}><DialogContent className="launch-source-dialog">{record && <><DialogTitle>{record.file}</DialogTitle><DialogDescription>Authored fictional source · {record.app} · {record.type} · {record.date}</DialogDescription><img className="launch-source-logo" src={'/providers/' + record.logo} alt={record.app}/><h4>Original example record</h4><p className="launch-source-text">{record.text}</p><p className="launch-source-boundary">This is the complete synthetic record used by this illustration, not an extract from a connected account. No original company records or live systems are loaded.</p><button className="launch-close-source" onClick={() => setSourceId(null)}><X size={15}/> Return to the investigation</button></>}</DialogContent></Dialog>
  </div>;
}
