// Authored demonstration only. No actual customer data or connected providers.
export const records = [
  { id: 'continuity', name: 'Rollout staffing & dependencies', date: 'May 7', author: 'Maya · Rollout lead; Priya · Operations', text: 'The Northstar rollout covers 40 customer branches. The staffing sheet allocates one implementation specialist to Northstar and to another customer during the same week. Maya flags the overlap; neither customer can assume exclusive capacity. Her stopping point is to compare a phased launch with a full delay. The sheet is shared with the launch team, not copied from private notes.' },
  { id: 'interviews', name: 'Northstar opportunity · launch commitments', date: 'May 6', author: 'Elena · Sales', text: 'The CRM opportunity records a target launch on May 20 for all 40 branches. The customer expects managers to invite staff without IT assistance. This is a sales account of customer expectations, not customer sign-off on a changed scope or a guarantee of technical readiness. A renewal conversation is scheduled after launch; revenue impact is not established.' },
  { id: 'support', name: 'NS-184 · Invitations fail after sign-in', date: 'May 7', author: 'Jon · Support', text: 'Support has six tickets from Northstar administrators: four report an access error after company sign-in; two cannot locate the invitation control. Those symptoms may have different causes. The six tickets are not a count of all affected users. Jon links the access-error cases to engineering issue ID-247; he does not attribute the navigation complaints to that defect.' },
  { id: 'engineering', name: 'ID-247 · Delayed access permissions', date: 'May 7', author: 'Leo · Engineering', text: 'The issue tracker reproduces a timing defect: a newly assigned administrator may sign in before access permissions finish updating. The fix depends on the identity service. The issue is marked In progress, not released. Engineering must pass company-sign-in tests before any rollout. This defect does not explain the two navigation complaints.' },
  { id: 'design', name: 'Invitation controls · prototype review', date: 'May 7', author: 'Sam · Design', text: 'The design file shows an alternative invitation control tested in a prototype with three internal colleagues. It may address discoverability, but no customer usability test has been run. Design review is not deployment evidence. Shipping this interface change would add scope to the engineering fix; it can also be investigated separately.' },
  { id: 'code', name: 'PR #82 · Permissions timing fix', date: 'May 9', author: 'Leo · Engineering; Nia · Security', text: 'The pull request passes unit tests, but the company-sign-in integration test is still pending. A green unit-test check does not mean the change is production-ready. Nia must review the access boundary; Leo owns release execution. Neither the support thread nor the sales commitment authorizes bypassing this gate.' },
  { id: 'proposal', name: 'Phased launch · options & AI draft', date: 'May 9', author: 'Maya · Rollout lead; Priya · Operations', text: 'The team compares delaying all 40 branches, launching everywhere with manual assistance, and a five-branch pilot after the identity fix passes review. The staffing sheet rules out promising intensive support to both customers at once. AI drafts an updated launch brief and Jira task descriptions. Maya removes its unsupported claim that tests are complete. The proposed pilot excludes the navigation redesign. Alex must decide scope and Elena must obtain customer agreement. AI may prepare work but cannot release code, change permissions, send customer commitments, or approve the pilot.' },
  { id: 'decision', name: 'Five-branch pilot · scoped approval', date: 'May 12', author: 'Alex · Launch owner; Elena · Sales; Nia · Security', text: 'After the integration test and security review pass, Alex approves five branches only. Elena records the customer agreeing to the phased scope. Priya reserves two support windows without taking the other customer’s allocation. The remaining 35 branches stay paused. Approval, customer agreement, and resource allocation are distinct records summarized in this thread; the thread is not proof the deployment occurred.' },
  { id: 'release', name: 'Release v2.8.1 · deployment log', date: 'May 13', author: 'Leo · Engineering', text: 'The release log records v2.8.1 deployed to the five approved branches after the required checks passed. Rollback remains available. The other 35 branches were not enabled. This verifies deployment scope, not whether administrators succeeded or whether the commercial launch succeeded.' },
  { id: 'results', name: 'Pilot sign-in & invitation events.csv', date: 'May 16', author: 'Product analytics · exported pilot events', text: 'The CSV export contains 18 administrator setup attempts across the five pilot branches. Fifteen completed invitations without assistance; three completed after Support helped them find the control. No permissions-timing error was observed in these 18 attempts. The sample is small, has no comparison group, and excludes the 35 paused branches. It cannot prove the issue is eliminated or measure revenue impact.' },
  { id: 'learning', name: 'Pilot review · next rollout and product work', date: 'May 17', author: 'Maya · Rollout lead; Leo · Engineering; Sam · Design; Elena · Sales', text: 'The team reviews the deployment log, event export and support follow-ups. The permissions fix and navigation question remain separate. Maya proposes a second wave subject to support capacity and customer agreement; Sam schedules a customer usability test rather than treating the internal prototype as validated. Sales revises its launch-readiness checklist. AI can reuse the reviewed constraints to draft the next wave’s tasks, but must recheck current staffing, access, and approval. No wider rollout or durable commercial benefit has yet been established.' },
];
export const providers: Record<string, { name: string; type: string; logo: string }> = {
  continuity: { name: 'Google Sheets', type: 'Staffing spreadsheet', logo: '/providers/google-sheets.png' },
  interviews: { name: 'HubSpot', type: 'CRM opportunity', logo: '/providers/hubspot.svg' },
  support: { name: 'Zendesk', type: 'Support ticket', logo: '/providers/zendesk.svg' },
  engineering: { name: 'Jira', type: 'Engineering issue', logo: '/providers/jira.svg' },
  design: { name: 'Figma', type: 'Design file · prototype', logo: '/providers/figma.svg' },
  code: { name: 'GitHub', type: 'Pull request · test checks', logo: '/providers/github.svg' },
  proposal: { name: 'Google Docs', type: 'Draft launch brief', logo: '/providers/google-docs.png' },
  decision: { name: 'Slack', type: 'Approval thread', logo: '/providers/slack.png' },
  release: { name: 'GitHub', type: 'Release & deployment log', logo: '/providers/github.svg' },
  results: { name: 'Google Sheets', type: 'CSV export · viewed in Sheets', logo: '/providers/google-sheets.png' },
  learning: { name: 'Google Docs', type: 'Reviewed learning record', logo: '/providers/google-docs.png' },
};
export const relationships: Record<string, string> = {
  continuity: 'Constrains scope: the same specialist is allocated twice.',
  interviews: 'Sets expectations: all 40 branches, not technical readiness.',
  support: 'Separates symptoms: access errors and hard-to-find controls.',
  engineering: 'Explains one symptom: access timing, not navigation.',
  design: 'Offers another route: a prototype, not a shipped solution.',
  code: 'Gates release: unit tests passed; sign-in test still pending.',
  proposal: 'Combines constraints into options; not approval.',
  decision: 'Authorizes five branches, not the full launch.',
  release: 'Confirms what shipped, not whether it worked for people.',
  results: 'Shows observed attempts, not a proven wider benefit.',
  learning: 'Carries reviewed lessons into three separate workstreams.',
};
export const stages = [
  {
    label: 'Untangle the situation', heading: 'One launch date. Several different problems.', status: 'Causes & constraints open',
    question: 'Is the rollout blocked by the product, the plan, or both?',
    answer: 'The CRM promises 40 branches. Zendesk reports two distinct symptoms; Jira reproduces only the access error. Figma explores navigation, while the staffing sheet exposes a shared specialist. These are connected constraints—not one root cause. Separate what needs a fix, a scope decision, and a capacity agreement.',
    idea: 'Separate access, usability, commitments, and capacity', note: 'A target date is not readiness; a prototype is not a released fix.',
    next: 'Ask Engineering about the access defect and Operations about the staffing overlap', left: 'Comparing a phased launch with a full delay; causes were not yet separated.',
    changed: 'Support found two different symptoms. Engineering reproduced one; Operations flagged double-booked capacity.',
    impact: 'A product fix alone may not make the full launch viable. Reconcile the customer promise and staffing plan too.',
    unknown: 'How many branches are affected, and can a narrower launch meet the customer’s needs?', record: 'support',
    sources: ['interviews','support','engineering','design','continuity'], date: 'May 7',
  },
  {
    label: 'Coordinate a responsible next move', heading: 'Move some work now. Keep the release conditional.', status: 'Pilot proposed · gates pending',
    question: 'What can we move forward without pretending the whole launch is ready?',
    answer: 'Compare a delay, a fully assisted launch, and a five-branch pilot. The staffing overlap makes full manual support unrealistic. GitHub shows unit tests passed, not the sign-in test. AI can draft the revised brief and Jira tasks while Engineering completes checks, Operations reserves capacity, and Sales seeks agreement. None of those parallel steps grants launch approval.',
    idea: 'Prepare a five-branch pilot; keep 35 branches paused', note: 'Integration test, security review, capacity, and customer agreement are still required.',
    next: 'Prepare the dependency checklist and task drafts; Alex decides scope after the gates clear', left: 'Separating the access defect, navigation question, and competing staffing commitments.',
    changed: 'A fix is in review. Its unit tests pass, but the sign-in test is pending. Maya corrected the AI’s claim that all tests were complete.',
    impact: 'Keep release conditional. Prepare a phased plan without promising a launch date or borrowing another customer’s support allocation.',
    unknown: 'Will the sign-in test pass, and will the customer accept the phased scope?', record: 'code',
    sources: ['interviews','continuity','engineering','code','design','proposal'], date: 'May 9',
  },
  {
    label: 'Learn across the work', heading: 'A bounded result. Several next directions.', status: 'Pilot reviewed · wider rollout open',
    question: 'What should change in the next rollout, the product, and our planning?',
    answer: 'The approval thread limits scope to five branches; the release log confirms that scope was deployed. The CSV records 18 attempts: 15 unaided, three with navigation help, and no observed access error. That informs the next rollout, a separate design test, and Sales’ readiness checklist. It does not prove all 40 branches are ready or that the pilot caused a business improvement.',
    idea: 'Plan the next wave; test navigation; revise launch commitments', note: 'Observed in five branches only. New scope still needs fresh checks and authority.',
    next: 'Draft the next-wave tasks from reviewed constraints; recheck staffing and customer agreement', left: 'A conditional five-branch pilot was proposed; no release had occurred.',
    changed: 'The required reviews passed, the customer agreed, and five branches were deployed. Pilot events and the cross-team review are available.',
    impact: 'Retain the access checks. Investigate navigation separately and carry the staffing constraint into the next wave.',
    unknown: 'Will the result hold across different branches? What will the customer usability test reveal?', record: 'results',
    sources: ['continuity','decision','release','results','design','learning'], date: 'May 17',
  },
];
